spring.datasource.url=jdbc:sqlite:library.db
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=octavian
spring.rabbitmq.password=octavian
librarylab6app.rabbitmq.queue=librarylab6app.queue1
librarylab6app.rabbitmq.exchange=librarylab6app.direct
librarylab6app.rabbitmq.routingkey=librarylab6app.routingkey